server:
  port: 8080

security:
  jwt:
    secret: "dev-secret-change-me-32-bytes-minimum!!!!"
    ttl-seconds: 3600
spring:
  profiles:
    active: h2
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:airattix;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update         # or create / create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2
  flyway:
    enabled: false
